import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Suspense } from 'react';
import { Header } from './_components/Header';
import { PageContextProvider } from './_components/Header/context';
import { ToastProvider } from './_components/ToastProvider';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<PageContextProvider>
					<Suspense fallback={<div>loading..</div>}>
						<Header />
						{children}
					</Suspense>
					<ToastProvider />
				</PageContextProvider>
			</body>
		</html>
	);
}
