services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app-dev
    restart: unless-stopped
    user: node
    volumes:
      - ../:/workspaces/app:cached
      - copilot_data:/home/node/.copilot
      - node_modules:/workspaces/app/node_modules
      - ~/.ssh:/home/node/.ssh:ro
    tty: true
    stdin_open: true
    command: sleep infinity

volumes:
  copilot_data:
  node_modules:
